### ISSUE TITLE
can we exclude pod from some namespace

### ISSUE THREAD

**Issue by prasenforu** [duyanghao/velero-volume-controller#3]
Nice project !!

can we exclude pod from some namespace?

**Comment by duyanghao** [comment]
@prasenforu Pod exclusion is not supported currently, but I guess this filter policy can be added easily since now this project is quite simple and small. I will do that later and welcome your PR if it is urgent.

**Comment by prasenforu** [comment]
Thanks !!

Few Questions:

Anyway can this controller to do annotation on POD controller (statefulset,Deplyment,Replicationcontroller,Daemonsed) apart from pod?

will it annotate existing pod ?

**Comment by duyanghao** [comment]
> Thanks !!
> 
> Few Questions:
> 
> Anyway can this controller to do annotation on POD controller (statefulset,Deplyment,Replicationcontroller,Daemonsed) apart from pod?
> 
> will it annotate existing pod ?

@prasenforu Currently, `velero-volume-controller` will **add annotation to all existing pods(regardless of the type) with volume**, could you give a more detailed description of your use cases? Is that a pod excluding prefix filter parameter like `pod-excluding-prefix` can help?

**Comment by prasenforu** [comment]
Recent observation if pod is annotated previously, looks like as per controller logs its again annotating.
But true that, its not putting double entry in annotation field.

is it the normal behavior? 
because in  my case some of PODs are in Statefulset and ready annotated in statefulset.

**Comment by duyanghao** [comment]
> Recent observation if pod is annotated previously, looks like as per controller logs its again annotating.
> But true that, its not putting double entry in annotation field.
> 
> is it the normal behavior?
> because in my case some of PODs are in Statefulset and ready annotated in statefulset.

Yeah, `velero-volume-controller` will add `velero restic backup annotation` to pods with volume whenever it receives ADD or UPDATE Pod Event, regardless of whether it exists in the pod or not, and it will overwrite the annotation when it already exists.

In addition, velero restic will backup the PersistentVolumeClaims only once when there are multiple backup annotations backend with the same PersistentVolumeClaims, refers to [Advanced research for velero with Restic Integration](https://duyanghao.github.io/velero/)

**Comment by prasenforu** [comment]
Thanks 👍
