### ISSUE TITLE
Annotation of pods which are started by a Job

### ISSUE THREAD

**Issue by sevenval-admins** [duyanghao/velero-volume-controller#6]
We are successfully using the Velero Volume Controller and are very happy to be able to automate the annotation process.

The only problem we have is that even Pods that have a Job resource as their owner will have an annotation added by the controller.

In this particular case, we have a Job resource that makes backups of the database. The Pod that does the backup writes the backup to a volume. When the Pod is started, the annotation is set. After the backup is finished, the Pod quits and gets the status Succeeded. If Velero then tries to do a restic backup of the volume, an error occurs.

Is it possible for the controller to remove the annotation when the Pod exits?

Or is there a much better solution to my problem?

**Comment by duyanghao** [comment]
@sevenval-admins First of all, velero will proceed to the backup even though one of podvolumebackups fails. 
>>Is it possible for the controller to remove the annotation when the Pod exits?
>>Or is there a much better solution to my problem?

IMO, maybe `velero-volume-controller` should only add annotation to running pod and drop relevant annotation when pod status changes. I will do that later and welcome your PR if it is urgent.

**Comment by sevenval-admins** [comment]
It is right that Velero continues with the backup. But the status at the end is PartiallyFailed, which is not good for monitoring the backups.

Unfortunately I can't contribute any PR, because my coding knowledge is not sufficient for that.

**Comment by fredgate** [comment]
@duyanghao I can try to look at that. But I don't know if I prefer to ignore pods controlled by a job or/and pod not running. The problem if we simply ignore not running pods, is that we can annotate a pod started by a job, and that this pods terminated during a velero backup.

**Comment by fredgate** [comment]
The controller add the annotation to a new pod. I think that it should remove the annotation when the pod is not tunning anymore (error, completed...). I think that it should not add the annotation while the pod is pending, because restic could not work with these pods.

About this issue, we can add a option in the config to choose if we want to exclude pod issued from a job.

I can start a pull request with these features.

**Comment by fredgate** [comment]
I opened a pull request for that. Can you take a look ?

**Comment by duyanghao** [comment]
@fredgate Thanks for your PR, I will verify it later.

**Comment by duyanghao** [comment]
@sevenval-admins `velero-volume-controller` now supports `excludeJobs` option, please try with this feature and feel free to reopen this issue if this problem remains unresolved

**Comment by sevenval-admins** [comment]
@duyanghao Great. Thanks. Will try the option.
